include $(MAKER_ROOT)/Makefile.env

# Caller can set CMAKE_VARS with "-DVAR=VAL" to pass options to cmake

CMAKE_VARS += \
	-DCMAKE_PREFIX_PATH=$(LLVM_ROOT) \
	-DCMAKE_MODULE_PATH=$(LLVM_ROOT)/share/llvm/cmake \

LLVM_DIR ?= llvm
LLVM_BLD_DIR ?= $(LLVM_DIR)/bld

MAKE_ARGS ?= -j4

all: llvm

llvm:
	mkdir -p $(LLVM_BLD_DIR)
	cd $(LLVM_BLD_DIR) && cmake $(CMAKE_VARS) .. && make $(MAKE_ARGS)

llvm.clean:
	rm -rf $(LLVM_BLD_DIR)

clean: llvm.clean

.PHONY: llvm llvm.clean
