# TODO: for now we only support GCC

ifeq ($(LIBCHAIN_ENABLE_DIAGNOSTICS),1)
CFLAGS += -DLIBCHAIN_ENABLE_DIAGNOSTICS
endif

CFLAGS += \
	-I$(LIBCHAIN_ROOT)/src/include \
	-I$(LIBMSP_ROOT)/src/include \

LFLAGS += \
	-L$(LIBCHAIN_ROOT)/bld/gcc \

LIBS += \
    -lchain \
