# Declare a dependency on a library
#
# This includes the library into the build and creates rules for making the
# library and cleaning it, as well as aggregate rules 'dep' and 'depclean'.
#
# Usage: $(eval $(call depend,libxxx))

define depend-rule

$(2)/$(1).a: $(2)
	make -e -C $$^

$(EXEC): $(2)/$(1).a
dep: $(2)/$(1).a

depclean_$(1): $(2)
	make -C $$^ clean
depclean: depclean_$(1)

endef

define depend
DEP_BUILD_DIR_$(1) = $(2)/bld/gcc
CFLAGS += -I$(2)/src/include
LFLAGS += -L$(DEP_BUILD_DIR_$(1))
LIBS += -l$(subst lib,,$(1))
$(call depend-rule,$(1),$$(DEP_BUILD_DIR_$(1)))
endef
