include $(MAKER_ROOT)/Makefile.env

VOLTAGE = 3300
DEVICE_IDX ?= 0

FET_DEVICE = /dev/ttyACM$(DEVICE_IDX)

ARGS = \
	-v $(VOLTAGE) \
	-d $(FET_DEVICE) \

flash: $(BIN)
	LD_LIBRARY_PATH=$(LIBMSP430_ROOT) mspdebug $(ARGS) tilib "prog $(BIN)"

power:
	LD_LIBRARY_PATH=$(LIBMSP430_ROOT) mspdebug $(ARGS) tilib "exit"
